#!/bin/bash
source .config

BUILD_ROOT=`pwd`

# Create source directory
if [ ! -d sources ]
then
    mkdir sources
fi

# Clone nginx from github
if [ ! -d sources/nginx/.git ]
then
    git clone git@github.com:nginx/nginx.git sources/nginx
fi

# Optionally download pcre from the official ftp server
if [ $USE_EXTERNAL_PCRE -ne 0 ] && [ ! -d sources/pcre ]
then
   cd sources
   Version=pcre-8.40
   File=$Version.tar.gz
   curl https://ftp.pcre.org/pub/pcre/$File >$File
   tar -xf $File 
   rm $File
   mv $Version pcre
   cd ..
fi

# Optionally clone openssl from github
if [ $USE_GIT_OPENSSL -ne 0 ] && [ ! -d sources/openssl/.git ]
then
    git clone git@github.com:openssl/openssl.git sources/openssl
fi

# Configure nginx
cd sources/nginx
auto/configure $NGINX_BUILD_FLAGS
make install
cd $BUILD_ROOT

