#!/bin/bash
source .config

# Configure the database layout
m4 -DROOT_PATH="$ROOT_PATH" -DMYSQL_PORT="$MYSQL_PORT" -DMYSQL_DATABASE_NAME="$MYSQL_DATABASE_NAME" conf/mysql/db.sql.m4 >conf/mysql/db.sql


DataPath=$ROOT_PATH/mysqld/data

if [[ -d "$DataPath" ]]
then
    echo "Database already installed, remove $DataPath to reinstall"
    exit 1 
fi

mkdir -p $ROOT_PATH/mysqld/data

echo "Stopping mysqld"
./run_mysqld stop

BaseDir=$(dirname `which mysqld`)
BaseDir=$(dirname $BaseDir)

# Install database
mysql_install_db --defaults-file="$MYSQL_CONFIG_PATH" --basedir="$BaseDir" --user=$USER --datadir="$DataPath"

# Change root password
InitScript=`dirname $MYSQL_CONFIG_PATH`/InitScript.sql
rm -f $InitScript
echo "SET PASSWORD FOR '$MYSQL_USER'@'localhost' = PASSWORD('$MYSQL_PASSWORD');">$InitScript
cat `dirname $MYSQL_CONFIG_PATH`/db.sql>>$InitScript
mysqld $MYSQL_ARGS --init-file=$InitScript &
PID=$!
sleep 1
kill $PID

