#!/bin/bash

MyPath=`dirname $0`
source $MyPath/.config

if [[ -f $MyPath/nginx ]]
then
    Nginx=$MyPath/nginx
else
    Nginx=nginx
fi

function failure()
{
    echo "Usage: run_nginx <start|stop|restart>"
    exit 1
}

if [[ "$#" -lt 1 ]]
then
    echo "not enough arguments provided $#, expected at least 1"
    failure
fi 

case $1 in
"start")
    "$Nginx" -p $ROOT_PATH -c $NGINX_CONFIG_PATH 
    ;;
"stop")
    "$Nginx" -p $ROOT_PATH -c $NGINX_CONFIG_PATH -s stop
    ;;
"reload" | "restart")
    "$Nginx" -p $ROOT_PATH -c $NGINX_CONFIG_PATH -s reload
    ;;
*)
    echo "Unknown action $1"
    failure
    ;;
esac

