#!/bin/bash
source .config

if [ ! -d $CERTBOT_WELL_KNOWN_PATH ]
then 
    mkdir -p $CERTBOT_WELL_KNOWN_PATH
fi

CommonArgs="--webroot --config-dir=$CERTBOT_CONFIG_PATH --work-dir=$ROOT_PATH --logs-dir=$ROOT_PATH/logs -w $CERTBOT_WELL_KNOWN_PATH"

certbot certonly $@ $CommonArgs -d $SERVER_NAME
certbot certonly $@ $CommonArgs -d $TDRZ_DATA_SUBDOMAIN.$SERVER_NAME

