#!/bin/bash

function failure()
{
    echo "Usage: run_mysqld <start|stop|restart>"
    exit 1
}

if [[ "$#" -lt 1 ]]
then
    echo "not enough arguments provided $#, expected at least 1"
    failure
fi 

source .config
MyPath=`dirname $0`
$MyPath/daemonize $1 $MyPath/logs/mysqld.pid mysqld $MYSQL_ARGS

