#!/bin/bash

MyPath=`dirname $0`
source $MyPath/.config

certbot=/usr/bin/certbot

# Make sure the well known path exists
if [ ! -d $CERTBOT_WELL_KNOWN_PATH ]
then 
    mkdir -p $CERTBOT_WELL_KNOWN_PATH
fi

CERTBOT_PARAMS="$CERTBOT_PARAMS --force-renewal --expand --webroot"

# $certbot certonly $@ $CERTBOT_PARAMS -w $CERTBOT_WELL_KNOWN_PATH -d $SERVER_NAME -d $TDRZ_DATA_SUBDOMAIN.$SERVER_NAME -d mail.$SERVER_NAME
# $certbot certonly $@ $CERTBOT_PARAMS -w $CERTBOT_WELL_KNOWN_PATH -d $COFFEE_SERVER_NAME -d www.$COFFEE_SERVER_NAME -d git.$COFFEE_SERVER_NAME -d lekker.$COFFEE_SERVER_NAME -d pma.$COFFEE_SERVER_NAME -d ak.$COFFEE_SERVER_NAME 
# $certbot certonly $@ $CERTBOT_PARAMS -w $CERTBOT_WELL_KNOWN_PATH -d $PORTFOLIO_SERVER_NAME -d www.$PORTFOLIO_SERVER_NAME
$certbot $CERTBOT_PARAMS renew 
