#!/bin/bash

BaseDir=$(dirname "$0")

# Refresh all certificates
su guus -c "$BaseDir/run_certbot"

# Restart web server as guus user
su guus -c "$BaseDir/run_nginx restart"

# Restart mail server
$BaseDir/../mail/restart

